//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Driver_Car", "Car", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.Car), "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Driver), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Driver_Event", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.Event), "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Driver), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Driver_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.User), "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Driver), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Passenger_Event", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.Event), "Passenger", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Passenger), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Passenger_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.User), "Passenger", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Passenger), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_User_Profile", "Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.Profile), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.User), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Comment_Event", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.Event), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Comment), true)]
[assembly: EdmRelationshipAttribute("MainDbModel", "FK_Comment_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarpoolSystem.User), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CarpoolSystem.Comment), true)]

#endregion

namespace CarpoolSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MainDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MainDbEntities object using the connection string found in the 'MainDbEntities' section of the application configuration file.
        /// </summary>
        public MainDbEntities() : base("name=MainDbEntities", "MainDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MainDbEntities object.
        /// </summary>
        public MainDbEntities(string connectionString) : base(connectionString, "MainDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MainDbEntities object.
        /// </summary>
        public MainDbEntities(EntityConnection connection) : base(connection, "MainDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Car> Cars
        {
            get
            {
                if ((_Cars == null))
                {
                    _Cars = base.CreateObjectSet<Car>("Cars");
                }
                return _Cars;
            }
        }
        private ObjectSet<Car> _Cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Driver>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Driver> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Passenger> Passengers
        {
            get
            {
                if ((_Passengers == null))
                {
                    _Passengers = base.CreateObjectSet<Passenger>("Passengers");
                }
                return _Passengers;
            }
        }
        private ObjectSet<Passenger> _Passengers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCars(Car car)
        {
            base.AddObject("Cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Driver driver)
        {
            base.AddObject("Drivers", driver);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Passengers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPassengers(Passenger passenger)
        {
            base.AddObject("Passengers", passenger);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="carId">Initial value of the CarId property.</param>
        /// <param name="carMake">Initial value of the CarMake property.</param>
        /// <param name="carModel">Initial value of the CarModel property.</param>
        /// <param name="carYear">Initial value of the CarYear property.</param>
        /// <param name="carColor">Initial value of the CarColor property.</param>
        /// <param name="totalSeats">Initial value of the TotalSeats property.</param>
        /// <param name="seatsLeft">Initial value of the SeatsLeft property.</param>
        public static Car CreateCar(global::System.Int32 carId, global::System.String carMake, global::System.String carModel, global::System.Int32 carYear, global::System.String carColor, global::System.Int32 totalSeats, global::System.Int32 seatsLeft)
        {
            Car car = new Car();
            car.CarId = carId;
            car.CarMake = carMake;
            car.CarModel = carModel;
            car.CarYear = carYear;
            car.CarColor = carColor;
            car.TotalSeats = totalSeats;
            car.SeatsLeft = seatsLeft;
            return car;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarId
        {
            get
            {
                return _CarId;
            }
            set
            {
                if (_CarId != value)
                {
                    OnCarIdChanging(value);
                    ReportPropertyChanging("CarId");
                    _CarId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarId");
                    OnCarIdChanged();
                }
            }
        }
        private global::System.Int32 _CarId;
        partial void OnCarIdChanging(global::System.Int32 value);
        partial void OnCarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CarMake
        {
            get
            {
                return _CarMake;
            }
            set
            {
                OnCarMakeChanging(value);
                ReportPropertyChanging("CarMake");
                _CarMake = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CarMake");
                OnCarMakeChanged();
            }
        }
        private global::System.String _CarMake;
        partial void OnCarMakeChanging(global::System.String value);
        partial void OnCarMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CarModel
        {
            get
            {
                return _CarModel;
            }
            set
            {
                OnCarModelChanging(value);
                ReportPropertyChanging("CarModel");
                _CarModel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CarModel");
                OnCarModelChanged();
            }
        }
        private global::System.String _CarModel;
        partial void OnCarModelChanging(global::System.String value);
        partial void OnCarModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarYear
        {
            get
            {
                return _CarYear;
            }
            set
            {
                OnCarYearChanging(value);
                ReportPropertyChanging("CarYear");
                _CarYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarYear");
                OnCarYearChanged();
            }
        }
        private global::System.Int32 _CarYear;
        partial void OnCarYearChanging(global::System.Int32 value);
        partial void OnCarYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CarColor
        {
            get
            {
                return _CarColor;
            }
            set
            {
                OnCarColorChanging(value);
                ReportPropertyChanging("CarColor");
                _CarColor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CarColor");
                OnCarColorChanged();
            }
        }
        private global::System.String _CarColor;
        partial void OnCarColorChanging(global::System.String value);
        partial void OnCarColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalSeats
        {
            get
            {
                return _TotalSeats;
            }
            set
            {
                OnTotalSeatsChanging(value);
                ReportPropertyChanging("TotalSeats");
                _TotalSeats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalSeats");
                OnTotalSeatsChanged();
            }
        }
        private global::System.Int32 _TotalSeats;
        partial void OnTotalSeatsChanging(global::System.Int32 value);
        partial void OnTotalSeatsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeatsLeft
        {
            get
            {
                return _SeatsLeft;
            }
            set
            {
                OnSeatsLeftChanging(value);
                ReportPropertyChanging("SeatsLeft");
                _SeatsLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsLeft");
                OnSeatsLeftChanged();
            }
        }
        private global::System.Int32 _SeatsLeft;
        partial void OnSeatsLeftChanging(global::System.Int32 value);
        partial void OnSeatsLeftChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_Car", "Driver")]
        public EntityCollection<Driver> Drivers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Driver>("MainDbModel.FK_Driver_Car", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Driver>("MainDbModel.FK_Driver_Car", "Driver", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentId">Initial value of the CommentId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Comment CreateComment(global::System.Int32 commentId, global::System.Int32 userId, global::System.Int32 eventId, global::System.String text)
        {
            Comment comment = new Comment();
            comment.CommentId = commentId;
            comment.UserId = userId;
            comment.EventId = eventId;
            comment.Text = text;
            return comment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentId
        {
            get
            {
                return _CommentId;
            }
            set
            {
                if (_CommentId != value)
                {
                    OnCommentIdChanging(value);
                    ReportPropertyChanging("CommentId");
                    _CommentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentId");
                    OnCommentIdChanged();
                }
            }
        }
        private global::System.Int32 _CommentId;
        partial void OnCommentIdChanging(global::System.Int32 value);
        partial void OnCommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Comment_Event", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Comment_Event", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Comment_Event", "Event").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Comment_Event", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("MainDbModel.FK_Comment_Event", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Comment_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Comment_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Comment_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Comment_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MainDbModel.FK_Comment_User", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Driver")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver object.
        /// </summary>
        /// <param name="driverId">Initial value of the DriverId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="carId">Initial value of the CarId property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        public static Driver CreateDriver(global::System.Int32 driverId, global::System.Int32 userId, global::System.Int32 carId, global::System.Int32 eventId)
        {
            Driver driver = new Driver();
            driver.DriverId = driverId;
            driver.UserId = userId;
            driver.CarId = carId;
            driver.EventId = eventId;
            return driver;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DriverId
        {
            get
            {
                return _DriverId;
            }
            set
            {
                if (_DriverId != value)
                {
                    OnDriverIdChanging(value);
                    ReportPropertyChanging("DriverId");
                    _DriverId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DriverId");
                    OnDriverIdChanged();
                }
            }
        }
        private global::System.Int32 _DriverId;
        partial void OnDriverIdChanging(global::System.Int32 value);
        partial void OnDriverIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarId
        {
            get
            {
                return _CarId;
            }
            set
            {
                OnCarIdChanging(value);
                ReportPropertyChanging("CarId");
                _CarId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarId");
                OnCarIdChanged();
            }
        }
        private global::System.Int32 _CarId;
        partial void OnCarIdChanging(global::System.Int32 value);
        partial void OnCarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_Car", "Car")]
        public Car Car
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("MainDbModel.FK_Driver_Car", "Car").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("MainDbModel.FK_Driver_Car", "Car").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Car> CarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("MainDbModel.FK_Driver_Car", "Car");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Car>("MainDbModel.FK_Driver_Car", "Car", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_Event", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Driver_Event", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Driver_Event", "Event").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Driver_Event", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("MainDbModel.FK_Driver_Event", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Driver_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Driver_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Driver_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MainDbModel.FK_Driver_User", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="startingTime">Initial value of the StartingTime property.</param>
        /// <param name="endingTime">Initial value of the EndingTime property.</param>
        /// <param name="startingAddress">Initial value of the StartingAddress property.</param>
        /// <param name="endingAddress">Initial value of the EndingAddress property.</param>
        /// <param name="destCity">Initial value of the DestCity property.</param>
        /// <param name="destState">Initial value of the DestState property.</param>
        /// <param name="startingState">Initial value of the StartingState property.</param>
        /// <param name="startingCity">Initial value of the StartingCity property.</param>
        /// <param name="days">Initial value of the Days property.</param>
        public static Event CreateEvent(global::System.Int32 eventId, global::System.String title, global::System.String startingTime, global::System.String endingTime, global::System.String startingAddress, global::System.String endingAddress, global::System.String destCity, global::System.String destState, global::System.String startingState, global::System.String startingCity, global::System.String days)
        {
            Event @event = new Event();
            @event.EventId = eventId;
            @event.Title = title;
            @event.StartingTime = startingTime;
            @event.EndingTime = endingTime;
            @event.StartingAddress = startingAddress;
            @event.EndingAddress = endingAddress;
            @event.DestCity = destCity;
            @event.DestState = destState;
            @event.StartingState = startingState;
            @event.StartingCity = startingCity;
            @event.Days = days;
            return @event;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                if (_EventId != value)
                {
                    OnEventIdChanging(value);
                    ReportPropertyChanging("EventId");
                    _EventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StartingTime
        {
            get
            {
                return _StartingTime;
            }
            set
            {
                OnStartingTimeChanging(value);
                ReportPropertyChanging("StartingTime");
                _StartingTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StartingTime");
                OnStartingTimeChanged();
            }
        }
        private global::System.String _StartingTime;
        partial void OnStartingTimeChanging(global::System.String value);
        partial void OnStartingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndingTime
        {
            get
            {
                return _EndingTime;
            }
            set
            {
                OnEndingTimeChanging(value);
                ReportPropertyChanging("EndingTime");
                _EndingTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndingTime");
                OnEndingTimeChanged();
            }
        }
        private global::System.String _EndingTime;
        partial void OnEndingTimeChanging(global::System.String value);
        partial void OnEndingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventInfo
        {
            get
            {
                return _EventInfo;
            }
            set
            {
                OnEventInfoChanging(value);
                ReportPropertyChanging("EventInfo");
                _EventInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventInfo");
                OnEventInfoChanged();
            }
        }
        private global::System.String _EventInfo;
        partial void OnEventInfoChanging(global::System.String value);
        partial void OnEventInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StartingAddress
        {
            get
            {
                return _StartingAddress;
            }
            set
            {
                OnStartingAddressChanging(value);
                ReportPropertyChanging("StartingAddress");
                _StartingAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StartingAddress");
                OnStartingAddressChanged();
            }
        }
        private global::System.String _StartingAddress;
        partial void OnStartingAddressChanging(global::System.String value);
        partial void OnStartingAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndingAddress
        {
            get
            {
                return _EndingAddress;
            }
            set
            {
                OnEndingAddressChanging(value);
                ReportPropertyChanging("EndingAddress");
                _EndingAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndingAddress");
                OnEndingAddressChanged();
            }
        }
        private global::System.String _EndingAddress;
        partial void OnEndingAddressChanging(global::System.String value);
        partial void OnEndingAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DestCity
        {
            get
            {
                return _DestCity;
            }
            set
            {
                OnDestCityChanging(value);
                ReportPropertyChanging("DestCity");
                _DestCity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DestCity");
                OnDestCityChanged();
            }
        }
        private global::System.String _DestCity;
        partial void OnDestCityChanging(global::System.String value);
        partial void OnDestCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DestState
        {
            get
            {
                return _DestState;
            }
            set
            {
                OnDestStateChanging(value);
                ReportPropertyChanging("DestState");
                _DestState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DestState");
                OnDestStateChanged();
            }
        }
        private global::System.String _DestState;
        partial void OnDestStateChanging(global::System.String value);
        partial void OnDestStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StartingState
        {
            get
            {
                return _StartingState;
            }
            set
            {
                OnStartingStateChanging(value);
                ReportPropertyChanging("StartingState");
                _StartingState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StartingState");
                OnStartingStateChanged();
            }
        }
        private global::System.String _StartingState;
        partial void OnStartingStateChanging(global::System.String value);
        partial void OnStartingStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StartingCity
        {
            get
            {
                return _StartingCity;
            }
            set
            {
                OnStartingCityChanging(value);
                ReportPropertyChanging("StartingCity");
                _StartingCity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StartingCity");
                OnStartingCityChanged();
            }
        }
        private global::System.String _StartingCity;
        partial void OnStartingCityChanging(global::System.String value);
        partial void OnStartingCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Days
        {
            get
            {
                return _Days;
            }
            set
            {
                OnDaysChanging(value);
                ReportPropertyChanging("Days");
                _Days = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Days");
                OnDaysChanged();
            }
        }
        private global::System.String _Days;
        partial void OnDaysChanging(global::System.String value);
        partial void OnDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_Event", "Driver")]
        public EntityCollection<Driver> Drivers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Driver>("MainDbModel.FK_Driver_Event", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Driver>("MainDbModel.FK_Driver_Event", "Driver", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Passenger_Event", "Passenger")]
        public EntityCollection<Passenger> Passengers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Passenger>("MainDbModel.FK_Passenger_Event", "Passenger");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Passenger>("MainDbModel.FK_Passenger_Event", "Passenger", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Comment_Event", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("MainDbModel.FK_Comment_Event", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("MainDbModel.FK_Comment_Event", "Comment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Passenger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Passenger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Passenger object.
        /// </summary>
        /// <param name="passengerId">Initial value of the PassengerId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="eventId">Initial value of the EventId property.</param>
        public static Passenger CreatePassenger(global::System.Int32 passengerId, global::System.Int32 userId, global::System.Int32 eventId)
        {
            Passenger passenger = new Passenger();
            passenger.PassengerId = passengerId;
            passenger.UserId = userId;
            passenger.EventId = eventId;
            return passenger;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PassengerId
        {
            get
            {
                return _PassengerId;
            }
            set
            {
                if (_PassengerId != value)
                {
                    OnPassengerIdChanging(value);
                    ReportPropertyChanging("PassengerId");
                    _PassengerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PassengerId");
                    OnPassengerIdChanged();
                }
            }
        }
        private global::System.Int32 _PassengerId;
        partial void OnPassengerIdChanging(global::System.Int32 value);
        partial void OnPassengerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                OnEventIdChanging(value);
                ReportPropertyChanging("EventId");
                _EventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventId");
                OnEventIdChanged();
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Passenger_Event", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Passenger_Event", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Passenger_Event", "Event").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("MainDbModel.FK_Passenger_Event", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("MainDbModel.FK_Passenger_Event", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Passenger_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Passenger_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Passenger_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MainDbModel.FK_Passenger_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MainDbModel.FK_Passenger_User", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="profileId">Initial value of the ProfileId property.</param>
        /// <param name="emails">Initial value of the Emails property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        public static Profile CreateProfile(global::System.Int32 profileId, global::System.String emails, global::System.DateTime createDate, global::System.String firstName, global::System.String lastName, global::System.Int64 phone)
        {
            Profile profile = new Profile();
            profile.ProfileId = profileId;
            profile.Emails = emails;
            profile.CreateDate = createDate;
            profile.FirstName = firstName;
            profile.LastName = lastName;
            profile.Phone = phone;
            return profile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfileId
        {
            get
            {
                return _ProfileId;
            }
            set
            {
                if (_ProfileId != value)
                {
                    OnProfileIdChanging(value);
                    ReportPropertyChanging("ProfileId");
                    _ProfileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProfileId");
                    OnProfileIdChanged();
                }
            }
        }
        private global::System.Int32 _ProfileId;
        partial void OnProfileIdChanging(global::System.Int32 value);
        partial void OnProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Emails
        {
            get
            {
                return _Emails;
            }
            set
            {
                OnEmailsChanging(value);
                ReportPropertyChanging("Emails");
                _Emails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Emails");
                OnEmailsChanged();
            }
        }
        private global::System.String _Emails;
        partial void OnEmailsChanging(global::System.String value);
        partial void OnEmailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.Int64 _Phone;
        partial void OnPhoneChanging(global::System.Int64 value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_User_Profile", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("MainDbModel.FK_User_Profile", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("MainDbModel.FK_User_Profile", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MainDbModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="profileId">Initial value of the ProfileId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="passwordSalt">Initial value of the PasswordSalt property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.Int32 profileId, global::System.String userName, global::System.String password, global::System.String passwordSalt)
        {
            User user = new User();
            user.UserId = userId;
            user.ProfileId = profileId;
            user.UserName = userName;
            user.Password = password;
            user.PasswordSalt = passwordSalt;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfileId
        {
            get
            {
                return _ProfileId;
            }
            set
            {
                OnProfileIdChanging(value);
                ReportPropertyChanging("ProfileId");
                _ProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfileId");
                OnProfileIdChanged();
            }
        }
        private global::System.Int32 _ProfileId;
        partial void OnProfileIdChanging(global::System.Int32 value);
        partial void OnProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                OnPasswordSaltChanging(value);
                ReportPropertyChanging("PasswordSalt");
                _PasswordSalt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordSalt");
                OnPasswordSaltChanged();
            }
        }
        private global::System.String _PasswordSalt;
        partial void OnPasswordSaltChanging(global::System.String value);
        partial void OnPasswordSaltChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Driver_User", "Driver")]
        public EntityCollection<Driver> Drivers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Driver>("MainDbModel.FK_Driver_User", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Driver>("MainDbModel.FK_Driver_User", "Driver", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Passenger_User", "Passenger")]
        public EntityCollection<Passenger> Passengers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Passenger>("MainDbModel.FK_Passenger_User", "Passenger");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Passenger>("MainDbModel.FK_Passenger_User", "Passenger", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_User_Profile", "Profile")]
        public Profile Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("MainDbModel.FK_User_Profile", "Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("MainDbModel.FK_User_Profile", "Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profile> ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("MainDbModel.FK_User_Profile", "Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profile>("MainDbModel.FK_User_Profile", "Profile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MainDbModel", "FK_Comment_User", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("MainDbModel.FK_Comment_User", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("MainDbModel.FK_Comment_User", "Comment", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
